### PR TITLE
Update submodules.

### PR DESCRIPTION
**Pull request by brianhuffman**

### CODE REVIEW

**Comment by brianhuffman** [comment]
It looks like a bunch of the saw-remote-api tests are failing with errors like `FileNotFoundError` or `ModuleNotFoundError`. I don't know if that's a real failure or just a transient server problem.

**Comment by RyanGlScott** [comment]
It's a Real Failure, but one that's happening on other PRs ([example](https://github.com/GaloisInc/saw-script/runs/3226205667)). My understanding is that #1402 aims to address this issue.

**Comment by brianhuffman** [comment]
Ok, in that case I guess I'll just wait for the other PR to be merged before this one.

**Review by atomb — APPROVED** [review]
This looks good to me if we can get CI to pass once we rebase this on top of a fixed build system that works for anything... I'm working on it!

**Pull request merged**
