### PR TITLE
Update cryptol

### PR DESCRIPTION
**Pull request by brianhuffman**
Update cryptol and cryptol-verifier submodules in parallel up to the latest versions.

### CODE REVIEW

**Comment by brianhuffman** [comment]
@kquick Another CI-related blocker seems to be the ghc-8.4 builds: The latest version of cryptol requires ghc-8.6 at a minimum, and does not support 8.4. Yet the CI build requires a successful 8.4 build in order to merge. What should we do about this?

**Comment by andreistefanescu** [comment]
@brianhuffman remove 8.4.4 from travis.yml

**Comment by brianhuffman** [comment]
If we remove 8.4.4, it seems like we should probably also add 8.8.3. Is there a reason we didn't do that before?

**Comment by kquick** [comment]
Dropping 8.4 was something we just decided was reasonable this week, so I definitely agree with Andrei.  

I think 8.8 got overlooked in the Travis CI because we are working to shift to github actions.  Adding it is fine, but if you end up with a lot of dependency issues, you could also leave it out because I don't think it's critical to this PR and we have non-travis confirmation that 8.8 is building right now.

**Comment by andreistefanescu** [comment]
ghc 8.8 requires cabal 3.0, and the travis haskell plugin does not support it. @chameco looked into it, and it was more work than it was worth it. We decided to wait for github actions.

**Pull request merged**
