### PR TITLE
Match the base pointer of llvm_elem and llvm_field.

### PR DESCRIPTION
**Pull request by andreistefanescu**
Currently, saw supports overrides of the form `llvm_execute_func [x_p, (llvm_elem x_p 1)];`, while it does not support overrides of the form `llvm_execute_func [(llvm_elem x_p 1), x_p];`, because matching on `llvm_elem x_p 1` fails unless `x_p` is already matched. This changes the handling of `llvm_elem` to match the base pointer. This changes the handling of `llvm_field` in a similar way.

### CODE REVIEW

**Comment by atomb** [comment]
Could you provide a bit more description of the goal of this PR?

**Comment by andreistefanescu** [comment]
@atomb I updated the description. Take a look at the tests, they are failing with the current version of saw.

**Review by brianhuffman — APPROVED** [review]
As I understand it, this patch basically makes `llvm_elem` and `llvm_field` work as patterns. So when you want to match `llvm_elem  n lhs` against `rhs`, that reduces to matching `lhs` against `rhs - offset` (where `offset` is computed from `n` and the pointer type).

I've thought about the possibility of implementing this before, and this is exactly how I would have done it. The code changes look good, so I think it's ready to merge as soon as we fix the test cases (which I'm going to have a look at now).

**Comment by brianhuffman** [comment]
When I run saw manually on `test0065_match_llvm_elem/test.saw`, it works just fine. But my `runtests.sh` says it fails; I think it must be running an out-of-date saw executable.

**Comment by andreistefanescu** [comment]
@brianhuffman the tests pass in github actions, and fail in travis because of missing external abc. The test added by this pull request passes in both. Or are you seeing a different failure?

I guess it's time to remove travis entirely.

**Comment by brianhuffman** [comment]
My local failure was bogus, due to an out-of-date saw binary. Everything seems to be working fine. We can safely ignore the failing travis integration test.

**Pull request merged**
