### PR TITLE
Find SMT array write of a fixed size.

### PR DESCRIPTION
**Pull request by andreistefanescu**

### CODE REVIEW

**Comment by kquick** [comment]
This fixed an issue for Amazon, but it fails on the s2n test, presumably due to available resources (memory, although it should be re-run to verify this).  Amazon keeps rebasing this on top of their stuff to keep things working.  Should we switch to internal runners to provide more memory because this just slipped us over the threshold, or is this a significant regression that needs addressing?

**Comment by kquick** [comment]
This has a crucible dependency: https://github.com/GaloisInc/crucible/pull/1074

**Comment by RyanGlScott** [comment]
Another `awslc` CI timeout occurred in https://github.com/GaloisInc/saw-script/pull/2018, which has comparatively fewer changes. I wonder if the `crucible` submodule bump is the culprit?

**Comment by RyanGlScott** [comment]
Superseded by #2037.

**Pull request closed without merging**
