### PR TITLE
Update submodules.

### PR DESCRIPTION
**Pull request by brianhuffman**

### CODE REVIEW

**Comment by RyanGlScott** [comment]
The next `cryptol` commits involve GaloisInc/cryptol#1207, which will require some changes to `saw-remote-api` to accommodate. When you get to that point, I have a branch [here](https://github.com/GaloisInc/saw-script/tree/bump-argo) which makes the necessary changes.

**Comment by RyanGlScott** [comment]
Is the [test failure in `cryptol-saw-core-tc-test`](https://github.com/GaloisInc/saw-script/pull/1317/checks?check_run_id=2742337355#step:11:19) expected?

```
Type error when checking "sort"
Inferred type
  sort 1
Not a subtype of expected type
  sort 0
For term
  (a' : sort 0)
-> (n' : Cryptol.Num)
-> (a'
    -> a'
    -> Prelude.Bool)
-> Cryptol.seq n' a'
-> Cryptol.seq n' a'
```

**Comment by brianhuffman** [comment]
No, that test failure was not expected. I suspect `cryptol-saw-core` might have an issue with universe levels when translating cryptol functions that use polymorphic recursion. I'll look into it.

**Comment by brianhuffman** [comment]
Well, it actually has nothing to do with polymorphic recursion, but rather with class dictionary types. For some reason `Eq` and `Cmp` class dictionaries are declared to be in `sort 1` rather than `sort 0`, and this is the root of the problem. I might need to open a separate ticket for this.

**Comment by brianhuffman** [comment]
Actually, it looks like it's not the dictionary types either. I'll put further discussion on a new ticket thread.

**Review by atomb — APPROVED** [review]
Now that #1318 is fixed, I see no reason not to merge this.

**Pull request merged**
