### PR TITLE
Allow duplicate method names in JVM verification

### LINKED ISSUE #212: Allow duplicate method names in Java
Currently, when attempting to load a method from a Java class, the name of that method must be unique. This is a frustrating limitation.

### PR DESCRIPTION
**Pull request by brianhuffman**
This patch adds new functionality to `crucible_jvm_verify` where if the class you're working with contains multiple methods with the same name, you can select the one you want by appending a type descriptor string to the method name. For example `"foo(II)Z"` chooses a method named `foo` with two integer arguments and a boolean result. Type descriptors are optional if the base name is unambiguous. In case a method name is ambiguous, the error message prints all the valid type descriptors that could be used to disambiguate.

Fixes #212.

### CODE REVIEW

**Comment by weaversa** [comment]
If you print the loaded module, does it display the names with these selectors?

**Comment by brianhuffman** [comment]
I didn't touch the printing code for `JavaClass` values in saw-script, nor did I test it. I'll have to go check to see what it does.

**Comment by weaversa** [comment]
> I didn't touch the printing code for `JavaClass` values in saw-script, nor did I test it. I'll have to go check to see what it does.

Thanks! I think this feature would be quite helpful.

**Comment by brianhuffman** [comment]
EDIT: Here's the output of printing the module `Test.class` from the test in this PR:
```
Class name: Test (super)
Superclass: java/lang/Object

Fields:
  default long val

Methods:
  void <init> ()
  void <init> (int)
  void <init> (long)
  long get ()
  void increment ()
  void increment (Test)
  void increment (int)
  void increment (long)
```
As you can see, it does list all the similarly-named methods separately, but it shows the types in pretty-printed form instead of the descriptor encoding.

**Comment by brianhuffman** [comment]
I think some extra information would be nice to add to printed `JavaClass` values, but I think I'll open a separate ticket for that instead of adding pretty-printing changes to this PR.

**Review by robdockins — APPROVED** [review]
This looks like a good improvement to me.  It would definitely be good to have some method to discover the appropriate descriptor names other than from the ambiguity error message.

**Pull request merged**
