### PR TITLE
Import both public and private Cryptol symbols

### PR DESCRIPTION
**Pull request by atomb**
It doesn't make sense to merge this until after #1018 is merged.

### CODE REVIEW

**Review by brianhuffman — APPROVED** [review]

**Comment by brianhuffman** [comment]
@atomb It looks like you need to bump the saw-core submodule to include GaloisInc/saw-core#120.

**Comment by atomb** [comment]
Oops. Yep, I do.

**Comment by atomb** [comment]
Ah, and I need to update the servers, too.

**Comment by brianhuffman** [comment]
It looks like your submodule bump includes not only GaloisInc/saw-core#120, but also the unrelated PR GaloisInc/saw-core#118. It turns out that 118 causes a performance regression in the saw-core typechecker, which is fixed by the yet-to-be-merged PR GaloisInc/saw-core#127.

To avoid the performance regression in saw-script master, I'd recommend bumping the saw-core submodule again to include GaloisInc/saw-core#127 (once it's merged, of course) before merging this PR.

**Comment by atomb** [comment]
Thanks for the heads-up @brianhuffman. In the interest of keeping `saw-script` aligned with the latest submodules whenever possible, I'll wait until GaloisInc/saw-core#127 is merged.

**Comment by brianhuffman** [comment]
It's already merged, so go ahead and do the further submodule bump.

**Comment by brianhuffman** [comment]
I just marked this as "next-to-merge" because I have some other changes that are blocked on this PR. Let's get this one done.

**Pull request merged**
