### PR TITLE
Search for uninterpreted names in both Cryptol and SAWCore naming environments

### PR DESCRIPTION
**Pull request by chameco**
Presently, specifying an uninterpreted name somewhat unintuitively searches first in the Cryptol environment and then in the SAWCore environment if the first search fails. This allows Cryptol names to "shadow" SAWCore names. This PR changes this scheme to search both environments, treating all names found as uninterpreted.

(This new approach is still far from ideal. We should consider adding more ways to precisely specify uninterpreted names, especially considering the new URI-based model for SAWCore names.)

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Does this fix a particular bug? If so, can a test case be added?

Also, does this patch change the warning observed in #1376?

**Comment by chameco** [comment]
I think this may actually fix the particular problem encountered in #1112, so I'll poke around and see if I can use that example as a test case. I don't suspect this will interact with #1376, but I'll try that out too.

**Review by andreistefanescu — APPROVED** [review]
👍

**Comment by chameco** [comment]
It looks like this does address the issue described in #1112.

**Comment by chameco** [comment]
@robdockins That's definitely unintentional - I'll take a look.

**Pull request merged**
