### PR TITLE
Update submodule versions.

### PR DESCRIPTION
**Pull request by brianhuffman**

### CODE REVIEW

**Comment by brianhuffman** [comment]
The ubuntu CI builds are failing with this message:
```
+ [[ Linux == \W\i\n\d\o\w\s ]]
+ IS_WIN=false
++ pwd
+ BIN=/home/runner/work/saw-script/saw-script/bin
+ EXT=
+ false
+ mkdir -p /home/runner/work/saw-script/saw-script/bin
+ COMMAND=build
+ shift
+ build
++ ghc --numeric-version
+ ghc_ver=9.0.1
+ cp cabal.GHC-9.0.1.config cabal.project.freeze
cp: cannot stat 'cabal.GHC-9.0.1.config': No such file or directory
Error: Process completed with exit code 1.
```

**Comment by RyanGlScott** [comment]
This is quite bizarre. `ghc_ver` comes from here:

https://github.com/GaloisInc/saw-script/blob/58ca144606e6e24e0f63c45169e2cdaec8dcda09/.github/ci.sh#L109-L110

This would suggest that CI is downloading GHC 9.0.1 somehow. Yet [the CI logs](https://github.com/GaloisInc/saw-script/pull/1455/checks?check_run_id=3610589461#step:5:15) disagree with this claim:

```
Installing ghc version 8.10.3
```

I have no idea how GHC 9.0.1 is ending up on the `PATH`.

**Comment by RyanGlScott** [comment]
I'm starting to suspect that this is a bug in [`haskell/actions`](https://github.com/haskell/actions/), since I am experiencing the same problem on a [completely different repo](https://github.com/GaloisInc/crucible/pull/851) ([logs](https://github.com/GaloisInc/crucible/pull/851/checks?check_run_id=3611068379)).

**Comment by atomb** [comment]
Strange that it's only doing that under Ubuntu. The bug is affecting Cryptol, too. We could add a `ghcup set ghc` line to `ci.sh` to work around it (and it wouldn't cause any harm to leave in, though it would be crufty). We'd have to do that in essentially all our Haskell builds on GitHub, though. Maybe we can hope they fix it soon?

**Comment by atomb** [comment]
Oh, @jared-w is the main contributor. Maybe we should bug him. :)

**Review by atomb — APPROVED** [review]
Looks good to me, and CI results are promising so far.

**Pull request merged**
