### PR TITLE
saw-script.el: define a comment syntax

### PR DESCRIPTION
**Pull request by siddharthist**
cc @david-christiansen 

Comments tested and working, I think my Emacs doesn't use tabs already so I'm not sure how to test that.

### CODE REVIEW

**Comment by atomb** [comment]
It might not make a difference as to whether or not to merge this, but it's perhaps worth pointing out that C-style block comments, between `/*` and `*/`, are also valid.

**Comment by siddharthist** [comment]
This only sets some comment-characters to be inserted when you hit the "comment the selection out" keybinding. I've never seen Emacs do smart switching between single-line and block comment markers, but that would be pretty sweet. David might know more, I'm new to Emacs hacking.

**Comment by david-christiansen** [comment]
Comments in Emacs modes should typically be set in two ways:
1. Via the syntax table, which allows syntactic font-lock to highlight them efficiently and allows the various editing commands to do the right thing (this happens [here](https://github.com/GaloisInc/saw-script/blob/625cf2e81022009670fc00d2b76b087061b478a5/saw-script.el#L80-L82)), and
2. In the variable that @siddharthist is setting, which is what controls the behavior of M-; and similar commands.

What's the reasoning for modifying `indent-tabs-mode`? Do tabs specifically break something here?

**Comment by david-christiansen** [comment]
(I think it's quite reasonable for M-; to do line comments rather than block comments, because it's typically used for temporarily commenting out little chunks of code)

**Comment by siddharthist** [comment]
No, I just thought it would be nice to encourage a consistent style for SAW users. I'm happy to take it or leave it.

**Comment by atomb** [comment]
Ah, yeah, I see now. I think `//` makes sense for `M-;` to use. Unless anyone has objections to `indent-tabs-mode`, I'm happy to merge.

**Comment by david-christiansen** [comment]
I don't think we should merge the `indent-tabs-mode` setting, unless tab characters actively break the language the way they do with layout syntax. Which I don't think they do here.

But the comment setting should definitely get merged.

**Pull request merged**
