### PR TITLE
Fall back to Z3 4.8.8 on AWSLC/BLST proofs

### PR DESCRIPTION
**Pull request by RyanGlScott**
This updates the `what4-solvers` snapshot to one that includes both Z3 4.8.8 and 4.8.14. While we continue to use 4.8.14 for most CI purposes, we fall back to 4.8.8 specifically when running the AWSLC or BLST proofs, which have been known to nondeterministically time out with those versions. Hopefully, this should resolve our CI woes.

This avoids the main issue in #1772, although the underlying cause still has yet to be investigated.

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Sadly, the OOM killer still activates on the AWSLC proofs even with Z3 4.8.14. I suppose we could try using Z3 4.8.8 next, as that is the Z3 version that is used in `aws-lc-verifications`'s `install.sh` script.

**Comment by RyanGlScott** [comment]
Well, the AWSLC/BLST proofs passed after downgrading to Z3 4.8.8. Let's see if this is consistent after restarting those jobs a couple of times...

**Comment by RyanGlScott** [comment]
With Z3 4.8.8, the AWSLC and BLST jobs have succeeded on three consecutive runs, which makes me cautiously optimistic. I've rebased everything, and assuming that this successful CI trend continues after this rebase, then I'm declaring victory.

**Comment by RyanGlScott** [comment]
Hot dog, I think it works! @chameco, does everything look good to you?

**Review by chameco — APPROVED** [review]
Thanks @RyanGlScott ! LGTM

**Comment by RyanGlScott** [comment]
@mergifyio refresh

**Pull request merged**
