### PR TITLE
Heapster ide info

### PR DESCRIPTION
**Pull request by scuellar**
This PR adds the `heapster_dump_ide_info` command to Heapster. The new instruction produces a `json` file with  Heapster permissions for each code block. The 'json' file can then be used by the [VSCode extension](https://gitlab-ext.galois.com/karl/vscode-heapster) to display the permissions on each block of source C code. 

This branch was developped a year ago and so the last handful of commits are bringing it up to date with master. We should merge it before it falls behind again. 

The key files to look at are:
* [IDESupport.hs](heapster-saw/src/Verifier/SAW/Heapster/IDESupport.hs) creates the structures that gather the permission logs that will be exported to `json`
* [JSONExport.hs](heapster-saw/src/Verifier/SAW/Heapster/JSONExport.hs) has the `JSON` instance declarations and the logic to export the permissions.
* [NamedMb.hs](heapster-saw/src/Verifier/SAW/Heapster/NamedMb.hs) Creates a wrapper around the old `Mb` that includes human readable names for variables, objects and code. Most of the changes are transforming `Mb` instances into `Mb'` instances
* [Implication.hs](heapster-saw/src/Verifier/SAW/Heapster/Implication.hs) has a new error type that is more descriptive and provides feedback when the derivation fails. This is passed to the `json` file and can be seen from the VSCode extension.

### CODE REVIEW

**Comment by eddywestbrook** [comment]
@scuellar it looks like the build is failing, due to some pattern-matching coverage warnings. Could you please take a shot at fixing these?

**Review by eddywestbrook — APPROVED** [review]
I worked closely with Karl and Eric M when they originally made this PR, so I'm pretty familiar with it. It adds some very useful functionality, specifically, the ability to export a JSON representation of a type-checked Crucible term, so that a UI can display that to the user.

**Comment by eddywestbrook** [comment]
Hmm, I'm now getting a seg fault on this branch on my local machine. Still debugging...

**Comment by eddywestbrook** [comment]
Never mind, it was a known issue with GHC 9.0. It works with GHC 8.10.4. So let's merge this sucker!

**Review by KarmaHaze — APPROVED** [review]
@karmahaze

**Pull request merged**
