### PR TITLE
Remove eq

### PR DESCRIPTION
**Pull request by robdockins**
Remove the dodgy `eq` saw-core primitive.  This causes some minor breakages in proofs that we'll need to fix up.

### CODE REVIEW

**Comment by brianhuffman** [comment]
I believe the merge conflicts should be resolved by simply rebasing this branch.

**Comment by robdockins** [comment]
Yeah, I think you're right.  I'm not quite ready to merge this yet, I'm still trying to fix up the proof breakages caused by this, and it's slow going.

**Review by brianhuffman — APPROVED** [review]
Looks good. It's nice to finally get rid of this `eq` operator.

**Comment by brianhuffman** [comment]
Make sure you're working with the latest version of the `blst` proofs, and with the latest z3 (4.8.10): #1115 updated the git commit hash for `blst`, and also the z3 version used in CI.

**Pull request merged**
