### PR TITLE
Incorporate Crucible updates affecting LLVM pointers

### PR DESCRIPTION
**Pull request by robdockins**
This merge request incorporates recent changes in Crucible that merge the representation of pointer values and machine-width bit vectors.

A previous attempt to merge this feature broke SAWScript proofs that involved 64-bit integers (see  #237), so let's be more careful about testing this branch before merging this time.

### CODE REVIEW

**Comment by TomMD** [comment]
An update to what I mentioned in chat.

For my tests with this branch and a ctlz patch I am getting `pattern match failure` which is a pretty printing of `PatternMatchFailureSimError`.  This is due to the second failure in `projectLLVM_pointer` - the pointer value is not in the expected form.

The pattern of the pointer I see is `VB Unassigned`, which I see we don't have a good translation for into `LLVMPtr` - not sure if there would be value in making a translation possible and being lazier with the failure.  This feedback isn't intended to impede the merge.

**Comment by robdockins** [comment]
Two points:

1) Do the error messages need improvement, or have they been sufficient to help diagnose the problem?
2) I'd be interested to take a look at the example causing problems and see if it is a case I think ought to work or not.

**Comment by TomMD** [comment]
1. I had to edit.  First I added a unique number (could have been an informative string) to each use of the error so I could identify where the error originated.  Second, I added a `HasCallStack` constraint everywhere there was `IsSym...` class - that proved to be entirely unhelpful as it only got the call from CrucibleBuiltin.hs.

2. I'll `scp` the example somewhere and send a pointer. The example remains largish, I'm not sure how to cut it down since prior minimization attempts lost the bug entirely.

**Comment by robdockins** [comment]
After discussions around the office, I've decided that this feature needs some significant refactoring to reduce the occurrences of special cases.

**Comment by TomMD** [comment]
I've re-tested with the new pulls and for my current target of interest I still see the same issue:

```
Loading file "/tmp/cisaw-work-dir15640/final.bc.saw"
Pointer arithmetic resulted in invalid pointer:
0x0:[64]
0x0:[64]
```

It might be that this code is undefined or has other issues that aren't of interest to the merge.

**Comment by TomMD** [comment]
Compiled with optimization the failure is quite different:

```
Loading file "/tmp/cisaw-work-dir15641/final.bc.saw"
at :584:33: invalid insertelement instruction
```

**Comment by robdockins** [comment]
This looks like two separate issues.

The first looks like some code path is adding the `0` offset to the null pointer.  This should probably be allowed, but currently fails because pointer arithmetic requires that the resulting pointer be 'valid'.  I guess we need a special case that says that pointer arithmetic is OK if the resulting pointer is valid OR is the null pointer.

The second issue is a bit harder to diagnose.  It looks like Clang has produced a code sequence that wants to `insertelement` into a 64-bit integer; as far as I know, that shouldn't be allowed. I expect there to be a `bitcast` or somesuch first.  Any chance we could isolate the problematic function and look at the LLVM assembly?

**Comment by TomMD** [comment]
> Any chance we could isolate the problematic function and look at the LLVM assembly?

I'll make that one of my jobs, but there is a good chance it won't be done before the new year.

**Comment by TomMD** [comment]
These latest commits get us farther and a new issue:

```
Loading file "/tmp/cisaw-work-dir9022/final.bc.saw"
arithmetic comparison on incompatible values
in ZSTD_compressContinue_internal at :1839:21
  In ZSTD_compressContinue_internal at :1839:21
```

Which is a result of the llvm:

```
  %119 = getelementptr inbounds i8, i8* %117, i64 %118, !dbg !3237
  %120 = load %struct.ZSTD_CCtx_s*, %struct.ZSTD_CCtx_s** %2, align 8, !dbg !3238
  %121 = getelementptr inbounds %struct.ZSTD_CCtx_s, %struct.ZSTD_CCtx_s* %120, i32 0, i32 2, !dbg !3239
  %122 = load i8*, i8** %121, align 8, !dbg !3239
  %123 = load %struct.ZSTD_CCtx_s*, %struct.ZSTD_CCtx_s** %2, align 8, !dbg !3240
  %124 = getelementptr inbounds %struct.ZSTD_CCtx_s, %struct.ZSTD_CCtx_s* %123, i32 0, i32 4, !dbg !3241
  %125 = load i32, i32* %124, align 4, !dbg !3241
  %126 = zext i32 %125 to i64, !dbg !3242
  %127 = getelementptr inbounds i8, i8* %122, i64 %126, !dbg !3242
  %128 = icmp ugt i8* %119, %127, !dbg !3243
```

Which is a result of the C code:

```
    if ((ip+srcSize > cctx->dictBase + cctx->lowLimit) & (ip < cctx->dictBase + cctx->dictLimit)) {
```

**Comment by robdockins** [comment]
@tommd, that's a pretty tricky semantics issue, I think.  It has to do with how defined the ordering test on pointers is/ought to be.  I don't think it should hold up this PR, but I think it's worth opening a separate ticket to track that issue.

**Pull request merged**
