### PR TITLE
CI quickfix: Pin libBF==0.5.1 in cabal.GHC-8.6.5.config

### PR DESCRIPTION
**Pull request by RyanGlScott**
For some reason, `libBF`'s version was not being pinned in `cabal.GHC-8.6.5-config`, causing CI to pick a build plan with `libBF-0.6`. This leads to the build error observed in https://github.com/GaloisInc/cryptol/pull/1055#issuecomment-771649363.

A quick fix for the issue to make sure that `libBF-0.5.1` is being picked in the 8.6.5 build plan, just like it is for other versions of GHC that CI tests. To this end, I manually inserted `any.libBF ==0.5.1` into `cabal.GHC-8.6.5-config`.

### CODE REVIEW

**Review by atomb — APPROVED** [review]
Looks good! I think Cryptol will be updated to work with 0.6 soon, so then we'll want to change this, but it might still be at least a few days until `saw-script` uses the updated Cryptol.

**Comment by RyanGlScott** [comment]
Well, that certainly fixed the error in the SAWScript - GHC v8.6.5 job. But now new build errors have arisen elsewhere! In particular, every `hmac`, `drbg`, `sike`, `bike`, `tls`, and `hmac-failure` job fails with [the following error](https://github.com/GaloisInc/saw-script/pull/1057/checks?check_run_id=1816938482#step:8:1028):

```
+ cp /saw-bin/saw /saw-script/s2n/test-deps/saw/bin/saw
+ /saw-script/s2n/test-deps/saw/bin/saw --version
/saw-script/s2n/test-deps/saw/bin/saw: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory
```

Curiously, none of the `awslc` nor `blst` jobs fail. Any ideas on what might be causing this, @jared-w?

**Comment by RyanGlScott** [comment]
Oh, I think I know what is happening! The `s2n-tests` jobs is configured to use `ubuntu-latest`, and at some point in the recent future, `ubuntu-latest` switched from Ubuntu 18.04 to 20.04. Compare [this successful job](https://github.com/GaloisInc/saw-script/runs/1810247103#step:1:4) to [this failing one](https://github.com/GaloisInc/saw-script/pull/1057/checks?check_run_id=1816938482#step:1:4).

Why does the version of Ubuntu matter? If I'm reading [this](https://github.com/GaloisInc/saw-script/pull/843) correctly, it's because these tests use a version of SAW built from a Debian-based Docker container into an Ubuntu-based container. My hypothesis is that whatever version of Debian that `s2nTests/docker/saw.dockerfile` is using and Ubuntu 18.04 both use the shared object file name `libtinfo.so.6`, but Ubuntu 20.04 likely uses a different name. It's unclear to me if the best fix is to:

1. Revert back to Ubuntu 18.04 everywhere
2. Symlink `libtinfo.so.6` somehow
3. Something else

**Comment by atomb** [comment]
Oh, that makes sense. I think that, for the meantime, specifying Ubuntu 18.04 specifically is probably a good approach. We probably want to get everything using 20.04 eventually, but given that it depends on the s2n build process, which is largely out of our control, I wouldn't want to be blocked on that update.

**Comment by RyanGlScott** [comment]
Ugh. I switched over all uses of `ubuntu-latest` to `ubuntu-18.04`, which made the GHC v8.6.5 job's test cases [start to fail](https://github.com/GaloisInc/saw-script/pull/1057/checks?check_run_id=1817507632#step:14:1162):

```
/home/runner/work/saw-script/saw-script/dist-newstyle/build/x86_64-linux/ghc-8.6.5/saw-script-0.7.0.99/build/saw/saw: error while loading shared libraries: libtinfo.so.6: cannot open shared object file: No such file or directory
tests passed: 5 / 98
```

To make things more confusing, this only happens with 8.6.5 in particular—8.8.4 and 8.10.2 appear unaffected.

**Comment by RyanGlScott** [comment]
https://github.com/GaloisInc/saw-script/pull/1057#issuecomment-772029755 is most likely happening because the 8.6.5 job was using cached libraries that were referencing different `.so` files than what Ubuntu 18.04 was expected. In other words, the 8.6.5 job entered a bad cache state.

Unfortunately, I'm not aware of a way to clear GitHub Actions' cache besides changing the keys used to index the cache itself. I confirmed in a [hacky, experimental commit](https://github.com/GaloisInc/saw-script/pull/1057/commits/43e032d181bd53d90c024dff77bf584c60265ed8) that changing the keys makes all the tests pass. I think all we can really do at this point is come up with a sensible way to change the keys that can be updated in the future if need be. @jared-w suggests prefixing the keys with `${{ env.cache_version }}-`, so I'll try that next.

**Pull request merged**
