### PR TITLE
Prepare release v1.2

### PR DESCRIPTION
**Pull request by mccleeary-galois**
Bump submodules, version numbers for both saw and saw-remote-api, update changelogs in preparation for SAW-1.2.

### CODE REVIEW

**Review by RyanGlScott — APPROVED** [review]
LGTM. I believe the coverage test CI failure is unrelated to these changes (but please open an issue about this so that we remember to look into it later).

**Review by RyanGlScott — CHANGES_REQUESTED** [review]
Oh wait, do make sure to bump the SAW Python bindings' version number in `pyproject.toml` as well.

**Comment by mccleeary-galois** [comment]
> Oh wait, do make sure to bump the SAW Python bindings' version number in `pyproject.toml` as well.

Updated.

**Comment by mccleeary-galois** [comment]
Added #2114 to capture the issue noted with compute coverage.

**Review by sauclovian-g — APPROVED** [review]
Oops, I haven't approved this edition.

Nothing further to comment on I think

**Review by kquick — APPROVED** [review]

**Review by RyanGlScott — APPROVED** [review]

**Pull request merged**
