### PR TITLE
Update for Cryptol that takes file reading procedure as a parameter

### PR DESCRIPTION
**Pull request by david-christiansen**
This is used for caching in the RPC API used by the Python bindings. This updates only Cryptol-related disk accesses (RE https://github.com/GaloisInc/cryptol/pull/793 and https://github.com/GaloisInc/cryptol-verifier/pull/23) - other source of disk access will need similar updates, but I figured it was better to get a branch merged in as soon as it was useful.

### CODE REVIEW

**Comment by david-christiansen** [comment]
Just merged in the main branch. The same number of integration tests fail locally as did prior to the merge - I think my machine has things like a too-new clang to make it go through all the way.

**Comment by david-christiansen** [comment]
Also, this is updated to point at more-recent Cryptol and cryptol-verifier commits, because those have had the appropriate PRs merged.

**Comment by brianhuffman** [comment]
There are currently some test failures that I believe are due to some cryptol changes that were merged before your parameterized-file-reader stuff. I think it's mostly a matter of merging the saw-script PRs in the right order; I'll see if I can get it all sorted today.

**Comment by atomb** [comment]
Thanks, @brianhuffman!

**Comment by brianhuffman** [comment]
The broken integration test is `test_w4`, and it starts failing when `cryptol` is updated to GaloisInc/cryptol#774, which changes how cryptol does defaulting. One of the indexing operators in `test_w4` is inferred with a different type, which happens to lead to a panic in the saw-core backend, due to GaloisInc/saw-core#59. I have a fix for that, which we'll have to get merged before I can do much else.

**Comment by brianhuffman** [comment]
If we merge #799 first, and then merge master into this branch again, then I think that should fix the broken tests.

**Comment by david-christiansen** [comment]
Thanks for the hard work, @brianhuffman!

**Pull request merged**
