### PR TITLE
Add `jvm_static_field_is` command for specifying static fields in JVM.

### LINKED ISSUE #908: Add support for JVM globals (i.e. static fields)
Currently SAW has no way to specify the contents of a static field in the pre- or post-state section of a `JVMSetup` block. We need to add support for this.

### LINKED ISSUE #925: Unhelpful error message on read of uninitialized field by `crucible_jvm_verify`
When verifying a JVM method, it may happen that the symbolic tries to read an instance field or an array element, and fails because the value is uninitialized. (This may happen due to a missing points-to declaration in the method spec, for example.) But the error message when this happens is quite uninformative:

```
[20:19:53.913] Stack trace:
"crucible_jvm_verify" (/Users/huffman/Work/saw-script/intTests/test_jvm_method_names/test.saw:15:1-15:20):
Symbolic execution failed.
Abort due to false assumption:
  internal: error: in Test.get
  incorrect variant
```

It just says "incorrect variant", and doesn't give any clue about what caused the problem, what it was trying to do when it happened, or how to fix it.

In this case, the error occurred because it was trying to read the field called `Test.val`, of type `long`, but that field was uninitialized because I commented out the points-to precondition for that field in the SAW spec. The error message should at least include the name of the field it was trying to access.

### PR DESCRIPTION
**Pull request by brianhuffman**
Fixes #908.

~~This PR also includes a crucible submodule update that fixes #925.~~

The crucible submodule update was included with #992.

### CODE REVIEW

**Comment by brianhuffman** [comment]
As currently implemented, the `jvm_static_field_is` statement takes a `JavaClass` value (obtained from `java_load_class`) and a `String` field name as its arguments. But perhaps it would be more convenient (and also more consistent with other `JVMSetup` commands) to just take a single `String` that can optionally include a class name qualifier. @atomb, what do you think?

**Comment by atomb** [comment]
I'd be inclined to implement the version that allows an arbitrary class name + field name string, partly because we may not otherwise have any other reason to load the class containing the static field. I think it might also be worth fixing the bug in `crucible-jvm` that causes one of the tests to fail. And so this can probably wait until after we release 0.7.

**Comment by brianhuffman** [comment]
Ok, then I think I'll mark this PR as a draft until I implement the qualified-name syntax for `jvm_static_field_is`.

**Review by atomb — APPROVED** [review]
This looks good. Thanks!

**Pull request merged**
