### PR TITLE
Implement a memory invalidation pass for jvm_verify

### LINKED ISSUE #900: JVM overrides that don't specify final values can lead to unsoundness
Currently we can prove an override for a JVM method with `crucible_jvm_verify` that specifies no final value for a field of an allocated object. The verification will still succeed if the method modifies such a field, but then executing the override will leave that field unmodified. This can lead to unsoundness.

To fix the problem, we should perform an invalidation pass and invalidate any allocated fields that do not have final values specified, as was implemented for LLVM in #549.

### PR DESCRIPTION
**Pull request by brianhuffman**
This is analogous to what was done for LLVM in #549, and prevents unsoundness caused by executing overrides with incomplete specs.

Fixes #900.

Note that this PR does not implement all the features exactly as they were discussed in the comment thread for #900: Currently, fields without points-to declarations in the post-state section are invalidated, rather than asserted to be equal to their initial values. The plan is to implement that feature separately, by having the same setup spec translate to a slightly different `MethodSpec` value when post-state points-to declarations are absent.

### CODE REVIEW

**Comment by brianhuffman** [comment]
It's likely that this PR in its current state will horribly break the ECDSA proof. If that's the case, then I should probably implement the additional features discussed in the #900 thread before merging this PR. I'll keep this in draft state until I know whether that will be necessary.

**Comment by brianhuffman** [comment]
The CI results show everything as passing, yet on my local repo `ecdsa.saw` fails somewhere in the middle (while verifying method `sq`). I thought that CI was running `ecdsa.saw`, so what's going on here?

**Comment by RyanGlScott** [comment]
It looks like `test_ecdsa` is specifically being excluded from CI :\

https://github.com/GaloisInc/saw-script/blob/9d812c91b6470f99df71fb25f499df08160014ac/.github/ci.sh#L171

**Comment by brianhuffman** [comment]
It looks like I was mistaken: `ecdsa.saw` (which is run by the `test_ecdsa` integration test) is specifically excluded from CI for some reason. https://github.com/GaloisInc/saw-script/blob/9d812c91b6470f99df71fb25f499df08160014ac/.github/ci.sh#L171

This kind of defeats the purpose of PR #932 and means that issue #901 is not really fixed.

**Comment by brianhuffman** [comment]
I've now opened #1070 to see if we can re-enable all the integration tests that were disabled in CI without explanation.

**Comment by brianhuffman** [comment]
Instead of doing an invalidation pass, I think we're going to want to implement per-field write permission bits in the crucible-jvm memory model. The explicit user-provided frame conditions required by this PR are just too onerous, and yield overrides that are not as generally applicable as we want.

**Comment by brianhuffman** [comment]
A memory invalidation pass is not the approach we want to take to fix this problem; we instead want to implement write permissions in the crucible-jvm memory model.

**Pull request closed without merging**
