### PR TITLE
Crucible memory fix

### PR DESCRIPTION
**Pull request by robdockins**
This is a (hopefully) temporary measure intended to address the memory consumption issues we are seeing in our CI jobs.

This incorporates the changes from both #797 and #668

### CODE REVIEW

**Comment by robdockins** [comment]
The SIKE test is now failing, but it seems to be the same failure as we are experiencing on `master`, so I guess it is unrelated?

**Review by andreistefanescu — APPROVED** [review]
@robdockins thank you! Lets's merge the crucible and macaw pull-requests, and then merge this.

**Comment by robdockins** [comment]
OK, I'll start pushing this up the stack.  Do you have any insight into what's going on with the SIKE proof?

**Comment by andreistefanescu** [comment]
it seems that sike broke with the change to the sbv bounds (https://github.com/GaloisInc/saw-script/pull/839). @jared-w is investigating.

**Comment by robdockins** [comment]
I think everything upstream is merged in now, this should be good to go.

**Comment by andreistefanescu** [comment]
@robdockins thanks, let's merge it!

**Pull request merged**
