### PR TITLE
Update cryptol and saw-core submodules to support exclusive enumerations.

### PR DESCRIPTION
**Pull request by brianhuffman**
This includes the following submodule PRs:
- GaloisInc/cryptol#1085 "exclusive-enumeration"
- GaloisInc/saw-core#188 "PLiteralLessThan"

### CODE REVIEW

**Comment by RyanGlScott** [comment]
FYI: This overlaps somewhat with #1137, which also bumps the `cryptol` submodule. I don't have a preference as to which one should land first.

**Comment by brianhuffman** [comment]
#1137 is not specifically related to explicit enumerations, is it? It just requires a version of cryptol that happens to come after the explicit enumerations patch, if I understand correctly.

**Comment by brianhuffman** [comment]
Which actual cryptol PR does #1137 depend on? I was intending to add more commits to this PR to bump the submodules as high as possible, but perhaps it's best if I bump up to the commit before the one that #1137 uses, so that the #1137 PR can include exactly the submodule PR that it needs.

**Comment by RyanGlScott** [comment]
It depends on GaloisInc/cryptol#1119.

**Comment by brianhuffman** [comment]
Ok, I bumped cryptol up to the revision immediately preceding GaloisInc/cryptol#1119. How about we merge #1137 next after this one?

**Review by RyanGlScott — APPROVED** [review]
> How about we merge #1137 next after this one?

Sounds good to me!

**Pull request merged**
