### PR TITLE
Replace deprecated GitHub Actions functions

### PR DESCRIPTION
**Pull request by LisannaAtGalois**
`add-path` and `set-env` have been deprecated as of 10/1/2020 and will be removed, this patch replaces them with environment files to keep the existing workflows running.

### CODE REVIEW

**Review by atomb — APPROVED** [review]
This looks good to me. Thanks!

**Comment by LisannaAtGalois** [comment]
@kquick @jared-w Failing travis build is blocking this PR. Should it be removed since GitHub Actions is used for this repo now? Also need to remove it from the [required status checks](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/enabling-required-status-checks) in the repo settings.

**Comment by kquick** [comment]
The travis test failure should be reflected in the Github Actions failures, so I'm concerned that it's not.  The error in the Travis build is because the `versions` package on Hackage was updated in a non-backward compatible method.   The `what4` dependency didn't have an upper bound on `version`, so it broke.  That has been fixed and merged on `what4` master, so the submodules update should fix travis.  

It's worth looking into why it doesn't fail for the github actions builds.

Longer term I think the travis build is almost ready to be retired, but I'd like @atomb to confirm that we don't need it anymore for nightly builds or Docker images.

**Comment by LisannaAtGalois** [comment]
> The travis test failure should be reflected in the Github Actions failures, so I'm concerned that it's not. The error in the Travis build is because the `versions` package on Hackage was updated in a non-backward compatible method. The `what4` dependency didn't have an upper bound on `version`, so it broke. That has been fixed and merged on `what4` master, so the submodules update should fix travis.
> 
> It's worth looking into why it doesn't fail for the github actions builds.
> 
> Longer term I think the travis build is almost ready to be retired, but I'd like @atomb to confirm that we don't need it anymore for nightly builds or Docker images.

@kquick I think that's because the `versions` version was frozen in this repo before it was updated on hackage, whereas travis doesn't use freeze files so it started grabbing the latest with the breaking change.

**Comment by jared-w** [comment]
> @kquick I think that's because the versions version was frozen in this repo before it was updated on hackage, whereas the travis CI doesn't use freeze files so it started grabbing the latest with the breaking change.

That would be correct, and why I like freeze files :)

**Pull request merged**
