### PR TITLE
Adapt to cryptol PR #1128 "persist-solver2"

### PR DESCRIPTION
**Pull request by brianhuffman**
This PR includes patches that adapt the saw-core package (taken from GaloisInc/saw-core#197) and saw-script package to work with GaloisInc/cryptol#1128, which adds support for a persistent solver connection for cryptol type checking (see #953).

However, this PR is not yet finished because the `saw-remote-api` package still needs to be adapted.

### CODE REVIEW

**Comment by robdockins** [comment]
It's worth noting that this PR doesn't actually use a persistent solver connection, it just updates the API uses.

**Comment by robdockins** [comment]
There a python-level error in the failing test here. https://github.com/GaloisInc/saw-script/pull/1267/checks?check_run_id=2615159214#step:14:76

I can't tell if this is related to my changes or not. @pnwamk, any insights?

**Comment by robdockins** [comment]
Well, fresh build looks like it passed, so I'm going to chalk that up to transient failure.

**Review by pnwamk — APPROVED** [review]
LGTM w.r.t. rpc server/client related changes

**Pull request merged**
