### PR TITLE
Updates flowing from cryptol PRs #1048 and #1136

### PR DESCRIPTION
**Pull request by robdockins**

### CODE REVIEW

**Comment by brianhuffman** [comment]
Might want to update the commit message so that github references the cross-repository PR numbers correctly: GaloisInc/cryptol#1048 and GaloisInc/cryptol#1191.

Also note that GaloisInc/cryptol#1128 "persist-solver2" precedes those two PRs and also contains breaking changes for saw-script (and saw-remote-api) so we'll have to address that one first.

**Comment by robdockins** [comment]
Whoops. Yeah, I'll fix those references via a rebase.

**Comment by robdockins** [comment]
This PR should land _after_ https://github.com/GaloisInc/saw-script/pull/1267 and will probably need some updating once it does.

**Comment by robdockins** [comment]
@brianhuffman, any chance you can take a look at this soon? I think it makes sense to merge this next.

**Review by brianhuffman — APPROVED** [review]
Looks good.

**Pull request merged**
