### PR TITLE
Handle x86 errors more gracefully

### LINKED ISSUE #678: "Invalid ELF header" error doesn't print location information
Running the `bike_r2` verification from s2n, I got the following error message (due to some C file not being compiled properly, I guess)
```
[22:21:02.577] Verifying bit_scan_reverse ...
[22:21:02.577] Simulating bit_scan_reverse ...
[22:21:02.715] Checking proof obligations bit_scan_reverse ...
Calling Yices to check sat
Running check sat
[22:21:02.729] Proof succeeded! bit_scan_reverse
[22:21:02.729] Finding symbol for "secure_cmp32"
[22:21:02.737] X86Error "Invalid ELF header"
```
The problem is that I expected the error message to be printed along with a saw-script call stack and saw-script source location information, but I got none.

Perhaps there is a mismatch of exception types in the x86 verification code compared to the saw-script exception handlers?

### PR DESCRIPTION
**Pull request by atomb**
And provide a template for catching other varieties of exception more
consistently.

Fixes #678.

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Is the idea to consolidate all of the exception-handling code into the `io` function? I ask since there are other places where `liftIO` is used in conjunction with `catch`:

https://github.com/GaloisInc/saw-script/blob/46249dbc7bae5f48623a709b1df1cc1ea002d4c5/src/SAWScript/Crucible/JVM/Override.hs#L971

https://github.com/GaloisInc/saw-script/blob/aac0a02121b05d3e93331d4cfb21ecefc461ad6a/src/SAWScript/Crucible/LLVM/Override.hs#L1845

Would it make sense to consolidate these bits of functionality into `io` as well?

**Comment by atomb** [comment]
I think it would make sense, unless anyone else knows of issues that might come up as a result of that. And there are almost 300 instances of `liftIO` in the `saw-script` repo that could probably be migrated. My current thought is that this PR lays the groundwork for doing that, but that we make the more sweeping changes after the 0.8 release.

**Comment by RyanGlScott** [comment]
That sounds reasonable to me. I suppose the only other thing I might desire from this PR is a test case that demonstrates the new error message, assuming that that is feasible to set up. If that's not feasible, then perhaps showing an example of the new error message in a GitHub comment would suffice.

**Comment by atomb** [comment]
Our current test infrastructure would make it a bit difficult to check the error message in this case. It would be nice to set something up to make that straightforward in the future, though. For the moment, here's an example of the error message I get from the code in this PR when I change the `ELF` text in an executable header to `EGF`:

````
[19:11:50.679] Loading file "/Users/atomb/galois/saw-script/intTests/test_llvm_x86_01/test.saw"
[19:11:50.684] Finding symbol for "foo"
[19:11:50.684] Stack trace:
"llvm_verify_x86" (/Users/atomb/galois/saw-script/intTests/test_llvm_x86_01/test.saw:14:20-14:35):
Error in x86 code: Invalid ELF header at offset 0: Invalid magic number for ELF: ("\DELEGF","\DELELF")
````

**Review by RyanGlScott — APPROVED** [review]
Excellent. We should open a separate issue about consolidating exception-handler–related code in `io`, but beyond that, LGTM.

**Pull request merged**
