### PR TITLE
Coq export

### PR DESCRIPTION
**Pull request by brianhuffman**
It's probably about time to merge the long-lived `coq-export` branch into `master`. This branch adds a few new commands to `saw` (marked "experimental") but shouldn't affect the behavior of any existing saw commands. It adds one new repository as a submodule, but doesn't pull in any new big haskell package dependencies.

### CODE REVIEW

**Comment by brianhuffman** [comment]
There were maybe 4 or 5 different breaking changes that I had to deal with. Doing it as a sequence of smaller merges was definitely easier than trying to figure it all out at once, but it did take a lot of compile time.

**Comment by eddywestbrook** [comment]
Well, @brianhuffman, I would certainly be interested to know what those changes were, as I am going to need to update the `wip-heapster` branch at some point...

**Comment by brianhuffman** [comment]
@eddywestbrook you should be able to see exactly what changes I had to make by looking at the commit messages on the merge commits in the `saw-script` repo. Also have a look at the commit logs in the `saw-core-coq` repo; as I updated it to work with newer versions of `saw-core` I made sure to mention in the commit message which `saw-core` PR I was adapting to.

**Comment by brianhuffman** [comment]
Thanks @kquick for fixing the CI builds!

**Pull request merged**
