### PR TITLE
Updates to track the `cex-errors2` branch of crucible

### PR DESCRIPTION
**Pull request by robdockins**
Along the way, deduplicate some functions that exist in essentially
the same form internally in crucible.

### CODE REVIEW

**Comment by robdockins** [comment]
Depends on:

https://github.com/GaloisInc/macaw/pull/153
https://github.com/GaloisInc/crucible/pull/511

**Comment by brianhuffman** [comment]
Let's get this PR merged next. We won't be able to bump the submodules further until we do.

**Comment by robdockins** [comment]
Makes sense to me.  Looks like we're blocked on the Travis build, but it seems to be the out-of-memory condition that's been plaguing those test builds rather than anything specifically related to this branch.

**Comment by andreistefanescu** [comment]
@robdockins actually, this seems related to this branch. It runs out of memory on fryingpan as well, despite the 32GB limit. @chameco is investigating.

**Comment by robdockins** [comment]
Interesting... I find that pretty surprising.  Let me know if I can help.

**Comment by chameco** [comment]
For some additional context, it looks like BIKE starts to fail on commit https://github.com/GaloisInc/crucible/pull/511/commits/d7e5503f2aaa0f747fcbdc5edb9520cfae6ef571. We're working to build a Docker container that runs the proofs so that this is easier to reproduce locally.

**Comment by robdockins** [comment]
I suppose this might be because memory-related verification conditions hold on to memory states longer following that patch.

**Comment by robdockins** [comment]
These changes were incorporated into #840

**Pull request closed without merging**
