### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by brianhuffman**

### CODE REVIEW

**Comment by brianhuffman** [comment]
There's a new failure in `aws-lc-verification` that I have just reproduced locally (and which doesn't happen in master). I'll investigate to see which submodule change causes the problem.

**Comment by brianhuffman** [comment]
The failure already happens in 58e511c83ceeb20c1c1802780b5e10edba130bc8, the first commit in this PR.

**Comment by brianhuffman** [comment]
Bisection on macaw shows that the failure is related to GaloisInc/macaw#183.

**Comment by chameco** [comment]
I believe that GaloisInc/aws-lc-verification@7f648fffe7a1f1097171279001ddab359a5749ab will resolve this for now, at least.

**Comment by brianhuffman** [comment]
It looks like that revision is working locally for me. I just pushed a patch to the dockerfile to use that revision, so I expect the CI tests to pass now. Thanks, @chameco!

Now that there's a reference to it from saw-script, we should make sure that git commit gets merged into the `aws-lc-verification` master branch, so that it won't disappear.

**Comment by brianhuffman** [comment]
Now the blst test has failed, probably due to #991. Perhaps we should merge a fix for that first.

**Review by andreistefanescu — APPROVED** [review]
👍

**Pull request merged**
