### PR TITLE
Newtype fix

### LINKED ISSUE #1256: Support for newtypes
Following the merge of https://github.com/GaloisInc/cryptol/pull/1015, we need to add support for newtypes to `cryptol-saw-core`.

As a first pass, we will simply erase newtypes.  They don't satisfy any typeclass constraints, so that part of the translation should be easy.

### PR DESCRIPTION
**Pull request by robdockins**
Fix support for record selectors applied to newtypes.  Fixes #1256.

### CODE REVIEW

**Review by atomb — APPROVED** [review]
I think this looks good, as long as it passes all the tests. It seems to also update the code to handle translation of the new Cryptol enumeration functions even though the description doesn't mention that. Was that intentional?

**Comment by robdockins** [comment]
Oops, not really.  I just accidentally branched from #1391 instead of master.

**Comment by atomb** [comment]
> Oops, not really. I just accidentally branched from #1391 instead of master.

Ah, yeah, Brian's probably the right one to review that code, anyway. :)

**Comment by robdockins** [comment]
Remaining failures seem unrelated, as best I can tell.

**Pull request merged**
