### PR TITLE
Merge saw-core repo

### PR DESCRIPTION
**Pull request by brianhuffman**
This merge pulls the previously-separate saw-core repository into the the saw-script repository, in its entirety and with all history intact.

### CODE REVIEW

**Comment by brianhuffman** [comment]
To facilitate reviewing, here are the commits made *after* the huge merge commit:
* 0f81527b1f20adb5a4526013c17618ec59702e6b
* 8f4eabdbc132f8a645cf9d56be5adc5f50f78be4
* c8a5b482b94559619db46faf66326fc53d6a0f9b

**Comment by brianhuffman** [comment]
Note: This PR includes the saw-core repo up to the commit that the saw-core submodule reference previously pointed to. It does not include the most-recently-merged PR GaloisInc/saw-core#197, which saw-script is not yet compatible with. The commit from this saw-core PR should be made into part of a new saw-script PR to adapt to the persistent solver features of cryptol.

**Comment by RyanGlScott** [comment]
Awesome! I think the only remaining hurdle is to make the `saw-core-coq`–related CI actions work properly, as they currently appear to [error out](https://github.com/GaloisInc/saw-script/pull/1213/checks?check_run_id=2439127442).

**Comment by brianhuffman** [comment]
It looks like @Ptival got the `saw-core-coq` CI tests working in GaloisInc/saw-core#195, and they were working for a while, but by GaloisInc/saw-core#203 they were failing again.

**Comment by brianhuffman** [comment]
By including the commits from GaloisInc/saw-core#201 and GaloisInc/saw-core#202, the saw-core-coq CI tests are now passing.

**Review by robdockins — APPROVED** [review]
Glad to see this going through.  I think it will save us a lot of effort in the end.

**Review by atomb — APPROVED** [review]
This looks good. I'm assuming all the added files are the same as the ones that were in the previous submodule and not reviewing them. :)

**Review by ldettwy — APPROVED** [review]
I can take the AR to converge this workflow with .github/workglows/ci.yml at some point.

**Pull request merged**
